// ─────────────────────────────────────────────
//  pages/Recommendations.jsx
// ─────────────────────────────────────────────
import React, { useEffect, useState } from "react";
import { BrainCircuit, Filter, RefreshCw, TrendingUp, TrendingDown, Minus } from "lucide-react";
import RecommendationCard from "../components/RecommendationCard";
import { fetchAllRecommendations } from "../services/api";

const FILTERS = ["ALL", "BUY", "HOLD", "SELL"];
const RISK_FILTERS = ["ALL", "Low", "Medium", "High"];

// ── Summary stat pill
function SummaryPill({ label, count, color, icon: Icon }) {
  return (
    <div className="glass rounded-xl p-4 flex items-center gap-3">
      <div className="w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0"
        style={{ background: `${color}15` }}>
        <Icon size={16} style={{ color }} />
      </div>
      <div>
        <p className="text-xs text-white/40">{label}</p>
        <p className="text-xl font-bold" style={{ fontFamily: "'Syne'", color }}>{count}</p>
      </div>
    </div>
  );
}

export default function Recommendations() {
  const [recs, setRecs]           = useState([]);
  const [loading, setLoading]     = useState(true);
  const [filter, setFilter]       = useState("ALL");
  const [riskFilter, setRiskFilt] = useState("ALL");
  const [sortBy, setSortBy]       = useState("confidence"); // confidence | date

  useEffect(() => {
    fetchAllRecommendations().then(data => {
      setRecs(data);
      setLoading(false);
    });
  }, []);

  const filtered = recs
    .filter(r => filter === "ALL" || r.recommendation === filter)
    .filter(r => riskFilter === "ALL" || r.riskLevel === riskFilter)
    .sort((a, b) =>
      sortBy === "confidence"
        ? b.confidence - a.confidence
        : new Date(b.timestamp) - new Date(a.timestamp)
    );

  const buyCount  = recs.filter(r => r.recommendation === "BUY").length;
  const sellCount = recs.filter(r => r.recommendation === "SELL").length;
  const holdCount = recs.filter(r => r.recommendation === "HOLD").length;

  return (
    <div className="space-y-6 pb-6">
      {/* ── Header ── */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white/90" style={{ fontFamily: "'Syne'" }}>
            AI Recommendations
          </h1>
          <p className="text-sm text-white/40 mt-0.5">
            Blockchain-verified recommendations generated by SecureStock AI v3.2
          </p>
        </div>
        <button onClick={() => { setLoading(true); fetchAllRecommendations().then(d => { setRecs(d); setLoading(false); }); }}
          className="btn-ghost flex items-center gap-2 px-4 py-2 rounded-lg text-sm">
          <RefreshCw size={13} /> Refresh
        </button>
      </div>

      {/* ── Summary pills ── */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <SummaryPill label="Total Recommendations" count={recs.length}  color="#00ffd1" icon={BrainCircuit} />
        <SummaryPill label="BUY Signals"            count={buyCount}    color="#00ff94" icon={TrendingUp} />
        <SummaryPill label="HOLD Signals"           count={holdCount}   color="#ffb020" icon={Minus} />
        <SummaryPill label="SELL Signals"           count={sellCount}   color="#ff4560" icon={TrendingDown} />
      </div>

      {/* ── Filters ── */}
      <div className="glass rounded-xl p-4 flex flex-wrap items-center gap-4">
        <div className="flex items-center gap-2">
          <Filter size={13} className="text-white/40" />
          <span className="text-xs text-white/40">Filter:</span>
        </div>

        {/* Recommendation type */}
        <div className="flex gap-1.5">
          {FILTERS.map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold transition-all duration-200"
              style={{
                fontFamily: "'DM Mono'",
                background: filter === f
                  ? f === "BUY" ? "rgba(0,255,148,0.2)" : f === "SELL" ? "rgba(255,69,96,0.2)" : f === "HOLD" ? "rgba(255,176,32,0.2)" : "rgba(0,255,209,0.15)"
                  : "rgba(255,255,255,0.05)",
                color: filter === f
                  ? f === "BUY" ? "#00ff94" : f === "SELL" ? "#ff4560" : f === "HOLD" ? "#ffb020" : "#00ffd1"
                  : "rgba(255,255,255,0.4)",
                border: filter === f ? "1px solid currentColor" : "1px solid transparent",
              }}>
              {f}
            </button>
          ))}
        </div>

        {/* Risk filter */}
        <div className="flex gap-1.5 ml-auto">
          <span className="text-xs text-white/30 self-center">Risk:</span>
          {RISK_FILTERS.map(r => (
            <button key={r} onClick={() => setRiskFilt(r)}
              className="px-2.5 py-1.5 rounded-lg text-xs transition-all duration-200"
              style={{
                fontFamily: "'DM Mono'",
                background: riskFilter === r ? "rgba(255,255,255,0.1)" : "rgba(255,255,255,0.03)",
                color: riskFilter === r ? "#fff" : "rgba(255,255,255,0.35)",
                border: riskFilter === r ? "1px solid rgba(255,255,255,0.2)" : "1px solid transparent",
              }}>
              {r}
            </button>
          ))}
        </div>

        {/* Sort */}
        <div className="flex items-center gap-2">
          <span className="text-xs text-white/30">Sort:</span>
          <select
            value={sortBy}
            onChange={e => setSortBy(e.target.value)}
            className="input-dark text-xs rounded-lg px-2 py-1.5"
            style={{ fontFamily: "'DM Mono'" }}
          >
            <option value="confidence">Confidence ↓</option>
            <option value="date">Date ↓</option>
          </select>
        </div>
      </div>

      {/* ── Cards grid ── */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {[1,2,3,4,5,6].map(i => <div key={i} className="glass rounded-xl h-56 animate-pulse" />)}
        </div>
      ) : filtered.length === 0 ? (
        <div className="glass rounded-xl p-12 text-center">
          <BrainCircuit size={36} className="mx-auto mb-3 text-white/20" />
          <p className="text-white/40 text-sm">No recommendations match your filters.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {filtered.map(rec => (
            <RecommendationCard key={rec.id} rec={rec} />
          ))}
        </div>
      )}

      {/* ── Result count ── */}
      {!loading && filtered.length > 0 && (
        <p className="text-xs text-white/30 text-center" style={{ fontFamily: "'DM Mono'" }}>
          Showing {filtered.length} of {recs.length} recommendations
        </p>
      )}
    </div>
  );
}
